services:
  admin:
    depends_on:
    - vhttp
    - vsql
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 500M
      restart_policy:
        condition: none
    environment:
      - CIVICRM_DATABASE
      - DRUPAL_DATABASE
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - VSITE
      - VSITE_ADMIN_MAIL
      - VSITE_ADMIN_NAME
      - VSITE_CIVICRM_VER
      - VSITE_DOMAIN
      - VSITE_NAME
      - VSITE_SITE
      - VSITE_SITE_NAME
    image: blackflysolutions/simuliidae-admin:7-apache-civicrm-5-stable
    volumes:
    - /var/www/drupal/git_deploy_cache:/tmp/git_deploy:rw
    - /var/www/drupal/7-host:/var/www/html/sites/all/host:ro
    - /var/www/drupal/libraries:/var/www/html/sites/all/libraries:ro
    - /var/www/drupal/7-modules:/var/www/html/sites/all/modules/contrib:ro
    - /var/www/drupal/7-features:/var/www/html/sites/all/modules/features:ro
    - /var/www/drupal/7-themes:/var/www/html/sites/all/themes/contrib:ro
    - vsite:/var/www/html/sites/default:rw
    - /var/www/civicrm/vendor:/var/www/html/vendor:ro
  vhttp:
    depends_on:
    - vsql
    deploy:
      labels:
        ca.civicrm.domain: '${VSITE_DOMAIN}'
      resources:
        limits:
          cpus: '1'
          memory: '${VSITE_HTTP_MEMORY-200M}'
      restart_policy:
        max_attempts: 2
    domainname: '${VSITE_DOMAIN}'
    environment:
      - CIVICRM_DATABASE
      - DRUPAL_DATABASE
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - VSITE
      - VSITE_DOMAIN
      - VSITE_SITE
    expose:
    - '80'
    image: blackflysolutions/drupal:7-apache-civicrm-5-stable
    ports:
    - 80/tcp
    volumes:
    - /var/www/drupal/git_deploy_cache:/tmp/git_deploy:rw
    - /var/www/drupal/7-host:/var/www/html/sites/all/host:ro
    - /var/www/drupal/libraries:/var/www/html/sites/all/libraries:ro
    - /var/www/drupal/7-modules:/var/www/html/sites/all/modules/contrib:ro
    - /var/www/drupal/7-features:/var/www/html/sites/all/modules/features:ro
    - /var/www/drupal/7-themes:/var/www/html/sites/all/themes/contrib:ro
    - vsite:/var/www/html/sites/default:rw
    - /var/www/civicrm/vendor:/var/www/html/vendor:ro
  vredis:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 120M
    image: ondemand_redis
  vsql:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: '${VSITE_SQL_MEMORY-600M}'
      restart_policy:
        condition: none
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    expose:
    - '3306'
    image: blackflysolutions/mariadb:10.1
    volumes:
    - vdb:/var/lib/mysql:rw
version: '3.0'
volumes:
  vdb: {}
  vsite: {}

