services:
  admin:
    depends_on:
    - vhttp
    - vsql
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2000M
      restart_policy:
        condition: none
    environment:
      CIVICRM_DATABASE: null
      DRUPAL_DATABASE: null
      MYSQL_DATABASE: null
      MYSQL_PASSWORD: null
      MYSQL_ROOT_PASSWORD: null
      MYSQL_USER: null
      VSITE: null
      VSITE_ADMIN_MAIL: null
      VSITE_ADMIN_NAME: null
      VSITE_CIVICRM_VER: null
      VSITE_DOMAIN: null
      VSITE_FEATURE: null
      VSITE_NAME: null
      VSITE_SITE: null
      VSITE_SITE_NAME: null
      VSITE_THEME: null
      VSITE_USER_MAIL: null
      VSITE_USER_NAME: null
      VSITE_USER_ROLE: null
    image: blackflysolutions/simuliidae-admin:7-apache
    volumes:
    - /home/drupal/.ssh:/home/drupal/.ssh:r
    - /var/www/drupal/git_deploy_cache:/tmp/git_deploy:rw
    - /var/backup/docker/${VSITE}/volume:/var/backup/volume:ro
    - /var/backup/docker/${VSITE}/vsql:/var/backup/vsql:ro
    - /var/backup/${VSITE_ADMIN_RESTOREDB_DIR-null}:/var/restore/vdb:ro
    - /var/backup/${VSITE_ADMIN_RESTORESITE_DIR-null}:/var/restore/vsite:ro
    - /var/www/drupal/7-host:/var/www/html/sites/all/host:ro
    - /var/www/drupal/libraries:/var/www/html/sites/all/libraries:ro
    - /var/www/civicrm/${VSITE_CIVICRM_VER-none}:/var/www/html/sites/all/modules/civicrm:ro
    - /var/www/drupal/7-modules:/var/www/html/sites/all/modules/contrib:ro
    - /var/www/drupal/7-features:/var/www/html/sites/all/modules/features:ro
    - /var/www/drupal/7-themes:/var/www/html/sites/all/themes/contrib:ro
    - vsite:/var/www/html/sites/default:rw
    - /var/www/civicrm/vendor:/var/www/html/vendor:ro
  vhttp:
    depends_on:
    - vsql
    deploy:
      labels:
        simuliidae.domain: '${VSITE_DOMAIN}'
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: '${VSITE_HTTP_MEMORY-500M}'
      restart_policy:
        max_attempts: 2
    environment:
      CIVICRM_DATABASE: null
      DRUPAL_DATABASE: null
      MYSQL_DATABASE: null
      MYSQL_PASSWORD: null
      MYSQL_ROOT_PASSWORD: null
      MYSQL_USER: null
      VSITE: null
      VSITE_DOMAIN: null
      VSITE_SITE: null
    expose:
    - '80'
    image: blackflysolutions/drupal:7-apache-civicrm-5
    ports:
    - 80/tcp
    volumes:
    - /var/www/drupal/git_deploy_cache:/tmp/git_deploy:rw
    - /var/www/drupal/7-host:/var/www/html/sites/all/host:ro
    - /var/www/drupal/libraries:/var/www/html/sites/all/libraries:ro
    - /var/www/civicrm/${VSITE_CIVICRM_VER-none}:/var/www/html/sites/all/modules/civicrm:ro
    - /var/www/drupal/7-modules:/var/www/html/sites/all/modules/contrib:ro
    - /var/www/drupal/7-features:/var/www/html/sites/all/modules/features:ro
    - /var/www/drupal/7-themes:/var/www/html/sites/all/themes/contrib:ro
    - vsite:/var/www/html/sites/default:rw
    - /var/www/civicrm/vendor:/var/www/html/vendor:ro
  vsql:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: '${VSITE_SQL_MEMORY-2000M}'
      restart_policy:
        max_attempts: 2
    environment:
      MYSQL_DATABASE: null
      MYSQL_PASSWORD: null
      MYSQL_ROOT_PASSWORD: null
      MYSQL_USER: null
    image: blackflysolutions/mariadb:10.1
    volumes:
    - vdb:/var/lib/mysql:rw
version: '3.0'
volumes:
  vdb: {}
  vsite: {}

